name: $name
version: $version
main: io.github.lumine1909.seasonsreload.SeasonsPlugin
api-version: $apiVersion
description: $description
load: STARTUP
authors:
  - Lumine1909
permissions:
  seasons.enable:
    default: op
  seasons.disable:
    default: op
  seasons.date.get:
    default: true
  seasons.date.set:
    default: op
